In [ ]:
import pandas as pd
import numpy as np

print("Libraries imported successfully")

Libraries imported successfully

In [4]:
import os

print(os.listdir('/content'))

['.config', 'train.csv', 'sample_data']

In [5]:
df = pd.read_csv('/content/train.csv')

print("Dataset loaded successfully!")
print("shape:",df.shape)

display(df.head())

Dataset loaded successfully!
shape: (891, 12)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [8]:
print("Missing values per column:")
display(df.isnull().sum())

print("Duplicate row:")
print(df.duplicated().sum())

print("\nData types:")
display(df.dtypes)

print("\nDataset information:")
df.info()

Missing values per column:

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Duplicate row:
0

Data types:

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [9]:
missing = df.isnull().sum()

print("Missing values before cleaning:")
display(missing[missing > 0])

Missing values before cleaning:

Age         177
Cabin       687
Embarked      2
dtype: int64

In [10]:
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

df = df.drop(columns=['Cabin'])

print("Missing values after cleaning:")
display(df.isnull().sum())

Missing values after cleaning:

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

I checked the missing values in the dataset and handles them based on the data.

In [13]:
duplicates = df.duplicated().sum()

print("Duplicate rows before cleaning:",duplicates)
df = df.drop_duplicates()

print("Duplicate rows after cleaning:",df.duplicated().sum())

Duplicate rows before cleaning: 0
Duplicate rows after cleaning: 0

I checked the dataset for duplicate rows and removed them to avoid repeated recors.This hepls to keep the dataset clean and give accurate analysis

In [14]:
print("Sex values:")
print(df['Sex'].unique())

print("\nEmbarked values:")
print(df['Embarked'].unique())

Sex values:
['male' 'female']

Embarked values:
['S' 'C' 'Q']

In [15]:
df['Sex'] = df['Sex'].str.strip().str.lower()
df['Embarked'] = df['Embarked'].str.strip().str.upper()

print("Standardisation completed.")
print(df['Sex'].unique())
print(df['Embarked'].unique())

Standardisation completed.
['male' 'female']
['S' 'C' 'Q']

I checked the values and made their format.
this hepls avoid prblems caused by different or extra spaces in the data

In [16]:
Q1 = df['Age'].quantile(0.25)
Q3 = df['Age'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[(df['Age'] < lower_bound) | (df['Age'] > upper_bound)]

print("Number of Age outliers:",len(outliers))

Number of Age outliers: 66

I used the IQR method to identify possible outliers in the age column.

In [17]:
print("Data types before correction:")
print(df.dtypes)

Data types before correction:
PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Embarked        object
dtype: object

In [18]:
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
df['Fare'] = pd.to_numeric(df['Fare'], errors='coerce')
df['Sex'] = df['Sex'].astype('string')
df['Embarked'] = df['Embarked'].astype('string')

print("Data types after correction:")
print(df.dtypes)

Data types after correction:
PassengerId             int64
Survived                int64
Pclass                  int64
Name                   object
Sex            string[python]
Age                   float64
SibSp                   int64
Parch                   int64
Ticket                 object
Fare                  float64
Embarked       string[python]
dtype: object

I checked the data types and corrected the important columns.This makes the dataset easier to analyse

In [21]:
print("Final Dataset Summary")
print("________________")
print("Rows:",df.shape[0])
print("Columns:",df.shape[1])
print("Missing Values:",df.isnull().sum().sum())
print("\nFinal data types:")
print(df.dtypes)

Final Dataset Summary
________________
Rows: 891
Columns: 11
Missing Values: 0

Final data types:
PassengerId             int64
Survived                int64
Pclass                  int64
Name                   object
Sex            string[python]
Age                   float64
SibSp                   int64
Parch                   int64
Ticket                 object
Fare                  float64
Embarked       string[python]
dtype: object

After cleaning the dataset,the missing values were handled,duplicate rows were removed,categorical values were standarised,and data type were corrected.
The cleaned dataset is now ready for analysis.

In [22]:
df.to_csv('Cleaned_titanic.csv',index=False)
print("Cleaned dataset saved successfully")

Cleaned dataset saved successfully

The cleaned dataset has been saved as a CSV file and is ready for the analysi.